name: 'Expect labels on PR'
author: 'Alexander Bocharov'
description: 'Check that specific labels are present on Pull Request and assign default one if not.'
branding:
  icon: 'tag'
  color: 'blue'
inputs:
  github-token:
    description: 'Your GitHub token. It should by set to secrets.GITHUB_TOKEN'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}